name: Update policy markdown

on:
    push: 
        branches:
            - main
        paths:
            - "windows/**"
            - "windows-applocker/**"
            - "windows-asr/**"
            - ".github/workflows/update-policymd.yml"
    workflow_dispatch:

jobs:
    markdown:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install modules
              shell: pwsh
              run: |
                Install-Module -Name "MarkdownPS" -Repository "PSGallery" -Scope "CurrentUser" -Force -AllowClobber

            - name: Update policy markdown
              shell: pwsh
              run: |
                $Paths = "${{ github.workspace }}/windows", "${{ github.workspace }}/windows-applocker", "${{ github.workspace }}/windows-asr"
                $Tables = $Paths | ForEach-Object {
                    $Path = $_
                    New-MDHeader -Text ($Path -replace "/home/runner/work/intune-baseline/", "") -Level 2
                    "`n"
                    Get-ChildItem -Path $Path -Recurse -Include "*.json" |
                    ForEach-Object { 
                        $File = $_
                        $Props = Get-Content -Path $File.FullName | `
                            ConvertFrom-Json | `
                            Select-Object -Property "name", "displayName", "description"
                        if ($null -ne $Props.description) {
                            [PSCustomObject] @{
                                Name        = $(if ($null -eq $Props.name) { $Props.displayName } else { $Props.name })
                                Description = $Props.description
                            }
                        }
                    } | New-MDTable -Shrink
                    "`n"
                } 

                $Content = @"
                # Policies

                $Tables
                "@
                $Content | Set-Content -Path "${{ github.workspace }}/POLICIES.md"

            - name: Commit changes
              id: commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "Update POLICIES.md"
                commit_user_name: "GitHub Action"
                commit_user_email: "git@stealthpuppy.com"
